actions:
## SSH Keys
  - action: command.run
    command: mkdir
    args:
      - "-p"
      - {{ user.home_dir }}/.ssh
  - action: command.run
    command: ssh-keygen
    args:
      - "-t"
      - ed25519
      - "-N ''"
      - "-f"
      - {{ user.home_dir }}/.ssh/git
  - action: command.run
    command: ssh-keygen
    args:
      - "-t"
      - ed25519
      - "-N ''"
      - "-f"
      - {{ user.home_dir }}/.ssh/id
  - action: command.run
    command: bash
    args:
      - "-c"
      - "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
