depends: ["./manifests/1-xcode"]
actions:
  # Add New Brew Taps
  - action: command.run
    command: brew
    args:
      - tap
      - "homebrew/cask-fonts"

  # System
  - action: package.install
    provider: homebrew
    list:
      - jq
      - tree
      - curl
      - dasel
      - curlie
      - wget
      - unzip
      - zip
      - gzip
      - git
      - xclip
      - rsync
      - fd
      - exa
      - pandoc
      - bzip2
      - shfmt
      - p7zip
      - gpg
      - openjdk
      - diffutils
      - topgrade
      - gtop
      - coreutils
      - the-unarchiver
  # Desktop Environment
  - action: package.install
    provider: homebrew
    list:
      - libreoffice
      - flameshot
      - keybase
      - bitwarden
      - alfred
      - vlc
      - linearmouse
      - balenaetcher
      - brave-browser
      - adobe-acrobat-reader
      - spotify
      - hiddenbar
      - alt-tab
      - beardedspice
      - gimp
      - simplenote
  # DevTools
  - action: package.install
    provider: homebrew
    list:
      - insomnia
      - neovim
      - neovide
      - visual-studio-code
      - rancher
  # Terminal
  - action: package.install
    provider: homebrew
    list:
      - lynx
      - alacritty
      - hstr
      - zsh
      - zsh-autosuggestions
      - zsh-history-substring-search
      - zsh-syntax-highlighting
      - "romkatv/powerlevel10k/powerlevel10k"
  # Fonts
  - action: package.install
    provider: homebrew
    repository: homebrew/cask-versions
    list:
      - font-hack-nerd-font
      - font-sauce-code-pro-nerd-font

  # Coding
  - action: package.install
    provider: homebrew
    list:
      - go
      - pyenv
      - yarn
      - rbenv
      - ruby-build
      - nodenv
      - node-build
  # VM
  - action: package.install
    provider: homebrew
    list:
      - vagrant
      - virt-manager
      - dnsmasq
      - qemu
      - libvirt
      - lima
  # Work Related
  - action: package.install
    provider: homebrew
    list:
      - awscli
      - pulumi
      - terraform
      - packer
      - iann0036/iamlive/iamlive
  # Install Pure Paste
  - action: command.run
    command: mas
    args:
      - "install"
      - "1611378436"
  # Install Better Snap Tool
  - action: command.run
    command: mas
    args:
      - "install"
      - "417375580"
