depends: ["./manifests/1-init", "./manifests/2-packages"]
actions:
  - action: command.run
    command: git
    args:
      - "clone"
      - "https://github.com/fabiomaia/linuxify.git"
      - "/tmp/linuxify"
  - action: command.run
    dir: /tmp/linuxify
    command: ./linuxify
    args:
      - "install"
