depends: ["./1-init", "./2-packages", "./3-linuxify"]
actions:
  - action: command.run
    command: nodenv
    args:
      - install
      - {{ variables.nodeVersion }}
  - action: command.run
    command: nodenv
    args:
      - global
      - {{ variables.nodeVersion }}