depends: ["./manifests/1-init", "./manifests/2-packages", "./manifests/3-linuxify"]
actions:
  - action: command.run
    command: nodenv
    args:
      - install
      - {{ variables.nodeVersion }}
  - action: command.run
    command: nodenv
    args:
      - global
      - {{ variables.nodeVersion }}