depends: ["./manifests/1-init", "./manifests/2-packages", "./manifests/3-linuxify"]
actions:
  - action: command.run
    command: pyenv
    args:
      - install
      - {{ variables.pythonVersion }}
  - action: command.run
    command: pyenv
    args:
      - global
      - {{ variables.pythonVersion }}
  - action: command.run
    command: pip3
    args:
      - install
      - --upgrade
      - pip
  - action: command.run
    command: pip3
    args:
      - install
      - pylint
