depends: ["./1-init", "./2-packages", "./3-linuxify"]
actions:
  - action: command.run
    command: rbenv
    args:
      - install
      - {{ variables.rubyVersion }}
  - action: command.run
    command: rbenv
    args:
      - global
      - {{ variables.rubyVersion }}