depends:
  [
    "./1-init",
    "./2-packages",
    "./3-linuxify",
    "./4-node",
    "./4-python",
    "./4-ruby",
  ]
actions:
  - action: file.copy
    from: alacritty/alacritty.yaml
    template: true
    to: "{{ user.home_dir }}/.config/alacritty/alacritty.yml"
  - action: file.copy
    from: alacritty/colors.yaml
    template: true
    to: "{{ user.home_dir }}/.config/alacritty/colors.yml"
  - action: file.copy
    from: alacritty/fonts.yaml
    template: true
    to: "{{ user.home_dir }}/.config/alacritty/fonts.yml"
  - action: file.copy
    from: alacritty/key_bindings.yaml
    template: true
    to: "{{ user.home_dir }}/.config/alacritty/key_bindings.yml"
  - action: file.copy
    from: hyper/hyper.js
    template: true
    to: "{{ user.home_dir }}/.hyper.js"
