depends:
  [
    "./manifests/1-init",
    "./manifests/2-packages",
    "./manifests/3-linuxify",
    "./manifests/4-node",
    "./manifests/4-python",
    "./manifests/4-ruby",
    "./manifests/5-terminal",
  ]
actions:
  - action: file.copy
    from: aliases.sh
    to: "{{ user.home_dir }}/.aliases"
  - action: file.copy
    from: zshrc
    to: "{{ user.home_dir }}/.zshrc"
  - action: file.copy
    from: exports.sh
    to: "{{ user.home_dir }}/.exports"
  - action: file.copy
    from: functions.sh
    to: "{{ user.home_dir }}/.functions"
  - action: file.copy
    from: path.sh
    to: "{{ user.home_dir }}/.path"
  - action: file.copy
    from: p10k.zsh
    to: "{{ user.home_dir }}/.p10k.zsh"
