depends:
  - 1-init
  - 2-packages
actions:
  - action: command.run
    command: mkdir
    args:
      - "-p"
      - {{ user.home_dir }}/Library/KeyBindings
  - action: file.copy
    from: library/DefaultKeyBinding.dict
    to: {{ user.home_dir }}/Library/KeyBindings/DefaultKeyBinding.dict

