depends:
  [
    "./1-init",
    "./2-packages",
    "./3-linuxify",
    "./4-node",
    "./4-python",
    "./4-ruby",
    "./5-terminal",
  ]
actions:
  - action: command.run
    command: mkdir
    args:
      - "-p"
      - {{ user.home_dir }}/Library/KeyBindings
  - action: file.copy
    from: library/DefaultKeyBinding.dict
    to: {{ user.home_dir }}/Library/KeyBindings/DefaultKeyBinding.dict

