depends:
  - 1-init
actions:
  - action: command.run
    command: mkdir
    args:
      - "-p"
      - {{ user.home_dir }}/Wallpapers
  - action: directory.copy
    from: Wallpapers/
    to: {{ user.home_dir }}/