depends:
  [
    "./manifests/1-init",
    "./manifests/2-packages",
    "./manifests/3-linuxify",
    "./manifests/4-node",
    "./manifests/4-python",
    "./manifests/4-ruby",
    "./manifests/5-terminal",
  ]
actions:
  - action: command.run
    command: mkdir
    args:
      - "-p"
      - {{ user.home_dir }}/Wallpapers
  - action: directory.copy
    from: Wallpapers/
    to: {{ user.home_dir }}/