depends:
  [
    "./1-init",
    "./2-packages",
    "./3-linuxify",
    "./4-node",
    "./4-python",
    "./4-ruby",
    "./5-terminal",
    "./6-dot-files",
    "./6-gitconfig",
    "./6-library",
    "./6-neovim",
    "./6-wallpaper",
  ]
actions:
  ###############################################################################
  # Time Machine                                                                #
  ###############################################################################
  # Prevent Time Machine from prompting to use new hard drives as backup volume
  - action: macos.default
    domain: com.apple.TimeMachine
    key: DoNotOfferNewDisksForBackup
    kind: bool
    value: "true"

  # Disable local Time Machine backups
  - action: command.run
    command: hash
    args:
      - "tmutil &> /dev/null"
  - action: command.run
    sudo: true
    command: tmutil
    args:
      - disablelocal
