depends:
  - 1-init
  - 2-packages
  - 3-linuxify
  - 4-node
  - 4-python
  - 4-ruby
actions:
  ###############################################################################
  # Mac App Store                                                               #
  ###############################################################################
  # Enable the automatic update check
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.SoftwareUpdate
      - AutomaticCheckEnabled
      - "-bool"
      - "true"
  # Check for software updates daily, not just once per week
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.SoftwareUpdate
      - ScheduleFrequency
      - "-int"
      - "1"
  # Download newly available updates in background
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.SoftwareUpdate
      - AutomaticDownload
      - "-int"
      - "1"
  # Install System data files & security updates
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.SoftwareUpdate
      - CriticalUpdateInstall
      - "-int"
      - "1"
