depends:
  [
    "./manifests/1-init",
    "./manifests/2-packages",
    "./manifests/3-linuxify",
    "./manifests/4-node",
    "./manifests/4-python",
    "./manifests/4-ruby",
    "./manifests/5-terminal",
    "./manifests/6-dot-files",
    "./manifests/6-gitconfig",
    "./manifests/6-library",
    "./manifests/6-neovim",
    "./manifests/6-wallpaper",
  ]
actions:
  ###############################################################################
  # Screen                                                                      #
  ###############################################################################
  # Enable subpixel font rendering on non-Apple LCDs
  # Reference: https://github.com/kevinSuttle/macOS-Defaults/issues/17#issuecomment-266633501
  - action: macos.default
    domain: NSGlobalDomain
    key: AppleFontSmoothing
    kind: int
    value: "1"

  # Enable HiDPI display modes (requires restart)
  - action: macos.default
    domain: /Library/Preferences/com.apple.windowserver
    key: DisplayResolutionEnabled
    kind: bool
    value: "true"

