depends:
  - 1-init
  - 2-packages
  - 3-linuxify
  - 4-node
  - 4-python
  - 4-ruby
actions:
  ###############################################################################
  # Activity Monitor                                                            #
  ###############################################################################
  ## Future Option
  # - action: macos.default
  # domain: NSGlobalDomain
  # key: NSDocumentSaveNewDocumentsToCloud
  # kind: bool
  # value: false

  # Show the main window when launching Activity Monitor
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.ActivityMonitor
      - IconType
      - "-bool"
      - "true"
  # Show all processes in Activity Monitor
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.ActivityMonitor
      - ShowCategory
      - "-int"
      - "0"
  # Sort Activity Monitor results by CPU usage
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.ActivityMonitor
      - SortColumn
      - "-string"
      - "CPUUsage"
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.ActivityMonitor
      - SortDirection
      - "-int"
      - "0"
