depends:
  - 1-init
  - 2-packages
  - 3-linuxify
  - 4-node
  - 4-python
  - 4-ruby
actions:
  ###############################################################################
  # Dock, Dashboard, and hot corners                                            #
  ###############################################################################
  # Minimize windows into their application’s icon
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.dock
      - minimize-to-application
      - "-bool"
      - "true"
  # Enable spring loading for all Dock items
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.dock
      - enable-spring-load-actions-on-all-items
      - "-bool"
      - "true"
  # Show indicator lights for open applications in the Dock
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.dock
      - show-process-indicators
      - "-bool"
      - "true"
  # Don’t animate opening applications from the Dock
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.dock
      - launchanim
      - "-bool"
      - "false"
  # Speed up Mission Control animations
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.dock
      - expose-animation-duration
      - "-float"
      - "0.1"
  # Don’t group windows by application in Mission Control
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.dock
      - expose-group-by-app
      - "-bool"
      - "false"
  # Don’t show Dashboard as a Space
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.dock
      - dashboard-in-overlay
      - "-bool"
      - "false"
  # Don’t automatically rearrange Spaces based on most recent use
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.dock
      - mru-spaces
      - "-bool"
      - "false"
  # Remove the auto-hiding Dock delay
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.dock
      - autohide-delay
      - "-float"
      - "0"
  # Remove the animation when hiding/showing the Dock
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.dock
      - autohide-time-modifier
      - "-float"
      - "0"
  # Automatically hide and show the Dock
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.dock
      - autohide
      - "-bool"
      - "true"
  # Make Dock icons of hidden applications translucent
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.dock
      - showhidden
      - "-bool"
      - "true"
  # Don’t show recent applications in Dock
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.dock
      - show-recents
      - "-bool"
      - "false"
