depends:
  - 2-packages
actions:
  ###############################################################################
  # General UI/UX                                                               #
  ###############################################################################
  # Disable the sound effects on boot

  - action: command.run
    sudo: true
    command: nvram
    args:
      - SystemAudioVolume=" "

  # Save to disk (not to iCloud) by default
  - action: macos.default
    domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    kind: bool
    value: "false"

  # Disable the "Are you sure you want to open this application?" dialog
  - action: macos.default
    domain: com.apple.LaunchServices
    key: LSQuarantine
    kind: bool
    value: "false"

  # Disable Resume system-wide
  - action: macos.default
    domain: com.apple.systempreferences
    key: NSQuitAlwaysKeepsWindows
    kind: bool
    value: "false"

  # Disable automatic capitalization as it's annoying when typing code
  - action: macos.default
    domain: NSGlobalDomain
    key: NSAutomaticCapitalizationEnabled
    kind: bool
    value: "false"

  # Disable smart dashes as they're annoying when typing code
  - action: macos.default
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    kind: bool
    value: "false"

  # Disable automatic period substitution as it's annoying when typing code
  - action: macos.default
    domain: NSGlobalDomain
    key: NSAutomaticPeriodSubstitutionEnabled
    kind: bool
    value: "false"

  # Disable smart quotes as they're annoying when typing code
  - action: macos.default
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    kind: bool
    value: "false"

  # Disable auto-correct
  - action: macos.default
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    kind: bool
    value: "false"
