depends:
  [
    "./1-init",
    "./2-packages",
    "./3-linuxify",
    "./4-node",
    "./4-python",
    "./4-ruby",
    "./5-terminal",
    "./6-dot-files",
    "./6-gitconfig",
    "./6-library",
    "./6-neovim",
    "./6-wallpaper",
  ]
actions:
  ###############################################################################
  # Photos                                                                      #
  ###############################################################################
  # Prevent Photos from opening automatically when devices are plugged in
  - action: macos.default
    domain: com.apple.ImageCaptur
    key: disableHotPlug
    kind: bool
    value: "true"
