depends:
  - 2-packages
actions:
  ###############################################################################
  # Mac App Store                                                               #
  ###############################################################################
  # Enable the automatic update check
  - action: macos.default
    domain: com.apple.SoftwareUpdate
    key: AutomaticCheckEnabled
    kind: bool
    value: "true"

  # Check for software updates daily, not just once per week
  - action: macos.default
    domain: com.apple.SoftwareUpdate
    key: ScheduleFrequency
    kind: int
    value: "1"

  # Download newly available updates in background
  - action: macos.default
    domain: com.apple.SoftwareUpdate
    key: AutomaticDownload
    kind: int
    value: "1"

  # Install System data files & security updates
  - action: macos.default
    domain: com.apple.SoftwareUpdate
    key: CriticalUpdateInstall
    kind: int
    value: "1"
