depends:
  [
    "./manifests/1-init",
    "./manifests/2-packages",
    "./manifests/3-linuxify",
    "./manifests/4-node",
    "./manifests/4-python",
    "./manifests/4-ruby",
    "./manifests/5-terminal",
    "./manifests/6-dot-files",
    "./manifests/6-gitconfig",
    "./manifests/6-library",
    "./manifests/6-neovim",
    "./manifests/6-wallpaper",
  ]
actions:
  ###############################################################################
  # Time Machine                                                                #
  ###############################################################################
  # Prevent Time Machine from prompting to use new hard drives as backup volume
  - action: macos.default
    domain: com.apple.TimeMachine
    key: DoNotOfferNewDisksForBackup
    kind: bool
    value: "true"

  # Disable local Time Machine backups
  - action: command.run
    command: hash
    args:
      - "tmutil &> /dev/null"
  - action: command.run
    sudo: true
    command: tmutil
    args:
      - disablelocal
