depends:
  [
    "./manifests/1-init",
    "./manifests/2-packages",
    "./manifests/3-linuxify",
    "./manifests/4-node",
    "./manifests/4-python",
    "./manifests/4-ruby",
    "./manifests/5-terminal",
    "./manifests/6-dot-files",
    "./manifests/6-gitconfig",
    "./manifests/6-library",
    "./manifests/6-neovim",
    "./manifests/6-wallpaper",
  ]
actions:
  ###############################################################################
  # Energy saving/Power Settings                                                #
  ###############################################################################
  - action: command.run
    sudo: true
    command: systemsetup
    args:
      - "-setrestartfreeze"
      - "on"
  - action: command.run
    sudo: true
    command: pmset
    args:
      - "-a"
      - displaysleep
      - "30"
  - action: command.run
    sudo: true
    command: pmset
    args:
      - "-c"
      - sleep
      - "0"
  - action: command.run
    sudo: true
    command: pmset
    args:
      - "-b"
      - sleep
      - "5"
  - action: command.run
    sudo: true
    command: pmset
    args:
      - "-a"
      - standbydelay
      - "86400"
  - action: command.run
    sudo: true
    command: systemsetup
    args:
      - "-setcomputersleep"
      - off
  - action: command.run
    sudo: true
    command: pmset
    args:
      - "-a"
      - hibernatemode
      - "0"
