depends:
  - 2-packages
actions:
  ###############################################################################
  # Photos                                                                      #
  ###############################################################################
  # Prevent Photos from opening automatically when devices are plugged in
  - action: macos.default
    domain: com.apple.ImageCaptur
    key: disableHotPlug
    kind: bool
    value: "true"
