depends:
  - 2-packages
actions:
  ###############################################################################
  # Activity Monitor                                                            #
  ###############################################################################
  ## Future Option
  # - action: macos.default
  # domain: NSGlobalDomain
  # key: NSDocumentSaveNewDocumentsToCloud
  # kind: bool
  # value: false

  # Show the main window when launching Activity Monitor
  - action: macos.default
    domain: com.apple.ActivityMonitor
    key: IconType
    kind: bool
    value: "true"

  # Show all processes in Activity Monitor
  - action: macos.default
    domain: com.apple.ActivityMonitor
    key: ShowCategory
    kind: int
    value: "0"

  # Sort Activity Monitor results by CPU usage
  - action: macos.default
    domain: com.apple.ActivityMonitor
    key: SortColumn
    kind: string
    value: "CPUUsage"

  - action: macos.default
    domain: com.apple.ActivityMonitor
    key: SortDirection
    kind: int
    value: "0"
