depends:
  - 1-init
  - 2-packages
  - 3-linuxify
  - 4-node
  - 4-python
  - 4-ruby
actions:
  ###############################################################################
  # Finder                                                                      #
  ###############################################################################
  # Finder: allow quitting via ⌘ + Q; doing so will also hide desktop icons
  - action: command.run
    command: defaults
    args:
      - "write"
      - "com.apple.finder"
      - "QuitMenuItem"
      - "-bool"
      - "true"
  # Finder: disable window animations and Get Info animations
  - action: command.run
    command: defaults
    args:
      - "write"
      - "com.apple.finder"
      - "DisableAllAnimations"
      - "-bool"
      - "true"
  # Don't Show icons for hard drives, servers, and removable media on the desktop
  - action: command.run
    command: defaults
    args:
      - "write"
      - "com.apple.finder"
      - "ShowExternalHardDrivesOnDesktop"
      - "-bool"
      - "false"
  - action: command.run
    command: defaults
    args:
      - "write"
      - "com.apple.finder"
      - "ShowHardDrivesOnDesktop"
      - "-bool"
      - "false"
  - action: command.run
    command: defaults
    args:
      - "write"
      - "com.apple.finder"
      - "ShowHardDrivesOnDesktop"
      - "-bool"
      - "false"
  - action: command.run
    command: defaults
    args:
      - "write"
      - "com.apple.finder"
      - "ShowRemovableMediaOnDesktop"
      - "-bool"
      - "false"
  # Finder: show hidden files by default
  - action: command.run
    command: defaults
    args:
      - "write"
      - "com.apple.finder"
      - "AppleShowAllFiles"
      - "-bool"
      - "false"
  # Finder: show all filename extensions
  - action: command.run
    command: defaults
    args:
      - "write"
      - "NSGlobalDomain"
      - "AppleShowAllExtensions"
      - "-bool"
      - "false"
  # Finder: show path bar
  - action: command.run
    command: defaults
    args:
      - "write"
      - "com.apple.finder"
      - "ShowPathbar"
      - "-bool"
      - "false"
  # Keep folders on top when sorting by name
  - action: command.run
    command: defaults
    args:
      - "write"
      - "com.apple.finder"
      - "_FXSortFoldersFirst"
      - "-bool"
      - "false"
  # When performing a search, search the current folder by default
  - action: command.run
    command: defaults
    args:
      - "write"
      - "com.apple.finder"
      - "FXDefaultSearchScope"
      - "-string"
      - "SCcf"
  # Disable the warning when changing a file extension
  - action: command.run
    command: defaults
    args:
      - "write"
      - "com.apple.finder"
      - "FXEnableExtensionChangeWarning"
      - "-bool"
      - "false"
  # Enable spring loading for directories
  - action: command.run
    command: defaults
    args:
      - "write"
      - "NSGlobalDomain"
      - "com.apple.springing.enabled"
      - "-bool"
      - "true"
  # Enable spring loading for directories
  - action: command.run
    command: defaults
    args:
      - "write"
      - "NSGlobalDomain"
      - "com.apple.springing.delay"
      - "-float"
      - "0"
  # Avoid creating .DS_Store files on network or USB volumes
  - action: command.run
    command: defaults
    args:
      - "write"
      - "com.apple.desktopservices"
      - "DSDontWriteNetworkStores"
      - "-bool"
      - "true"
  - action: command.run
    command: defaults
    args:
      - "write"
      - "com.apple.desktopservices"
      - "DSDontWriteUSBStores"
      - "-bool"
      - "true"

# # Disable disk image verification
# defaults write com.apple.frameworks.diskimages skip-verify -bool true
# defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
# defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

# # Use list view in all Finder windows by default
# # Four-letter codes for the other view modes: `icnv`, `clmv`, `glyv`
# defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

# # Show the ~/Library folder
# chflags nohidden ~/Library && xattr -d com.apple.FinderInfo ~/Library

# # Show the /Volumes folder
# sudo chflags nohidden /Volumes

# # Expand the following File Info panes:
# # “General”, “Open with”, and “Sharing & Permissions”
# defaults write com.apple.finder FXInfoPanesExpanded -dict \
# 	General -bool true \
# 	OpenWith -bool true \
# 	Privileges -bool true