depends:
  - 1-init
  - 2-packages
  - 3-linuxify
  - 4-node
  - 4-python
  - 4-ruby
actions:
  ###############################################################################
  # Time Machine                                                                #
  ###############################################################################
  # Prevent Time Machine from prompting to use new hard drives as backup volume
  - action: command.run
    command: defaults
    args:
      - write
      - com.apple.TimeMachine
      - DoNotOfferNewDisksForBackup
      - "-bool"
      - "true"
  # Disable local Time Machine backups
  - action: command.run
    command: hash
    args:
      - "tmutil &> /dev/null"
  - action: command.run
    sudo: true
    command: tmutil
    args:
      - disablelocal
