depends:
  - 2-packages
actions:
  ###############################################################################
  # Screen                                                                      #
  ###############################################################################
  # Enable subpixel font rendering on non-Apple LCDs
  # Reference: https://github.com/kevinSuttle/macOS-Defaults/issues/17#issuecomment-266633501
  - action: macos.default
    domain: NSGlobalDomain
    key: AppleFontSmoothing
    kind: int
    value: "1"

  # Enable HiDPI display modes (requires restart)
  - action: macos.default
    domain: /Library/Preferences/com.apple.windowserver
    key: DisplayResolutionEnabled
    kind: bool
    value: "true"

