depends:
  [
    "./1-init",
    "./2-packages",
    "./3-linuxify",
    "./4-node",
    "./4-python",
    "./4-ruby",
    "./5-terminal",
    "./6-dot-files",
    "./6-gitconfig",
    "./6-library",
    "./6-neovim",
    "./6-wallpaper",
  ]
actions:
  ###############################################################################
  # Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
  ###############################################################################
  # Increase sound quality for Bluetooth headphones/headsets
  - action: macos.default
    domain: com.apple.BluetoothAudioAgent
    key: "Apple Bitpool Min (editable)"
    kind: int
    value: "40"

  # Trackpad: enable tap to click for this user and for the login screen
  - action: macos.default
    domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    key: TrackpadCornerSecondaryClick
    kind: int
    value: "2"

  - action: macos.default
    domain: NSGlobalDomain
    key: com.apple.trackpad.trackpadCornerClickBehavior
    kind: int
    value: "1"

  - action: macos.default
    domain: NSGlobalDomain
    key: com.apple.trackpad.enableSecondaryClick
    kind: bool
    value: "true"

  # Disable "natural" (Lion-style) scrolling
  - action: macos.default
    domain: NSGlobalDomain
    key: com.apple.swipescrolldirection
    kind: bool
    value: "false"

  # Enable full keyboard access for all controls
  - action: macos.default
    domain: NSGlobalDomain
    key: AppleKeyboardUIMode
    kind: int
    value: "3"

  # Set the timezone; see `sudo systemsetup -listtimezones` for other values
  - action: command.run
    sudo: true
    command: systemsetup
    args:
      - "-settimezone"
      - "America/Oklahoma"
