depends:
  [
    "./1-init",
    "./2-packages",
    "./3-linuxify",
    "./4-node",
    "./4-python",
    "./4-ruby",
    "./5-terminal",
    "./6-dot-files",
    "./6-gitconfig",
    "./6-library",
    "./6-neovim",
    "./6-wallpaper",
  ]
actions:
  ###############################################################################
  # Dock, Dashboard, and hot corners                                            #
  ###############################################################################
  # Minimize windows into their application's icon
  - action: macos.default
    domain: com.apple.dock
    key: minimize-to-application
    kind: bool
    value: "true"

  # Enable spring loading for all Dock items
  - action: macos.default
    domain: com.apple.dock
    key: enable-spring-load-actions-on-all-items
    kind: bool
    value: "true"

  # Show indicator lights for open applications in the Dock
  - action: macos.default
    domain: com.apple.dock
    key: show-process-indicators
    kind: bool
    value: "true"

  # Don't animate opening applications from the Dock
  - action: macos.default
    domain: com.apple.dock
    key: launchanim
    kind: bool
    value: "false"

  # Speed up Mission Control animations
  - action: macos.default
    domain: com.apple.dock
    key: expose-animation-duration
    kind: float
    value: "0.1"

  # Don't group windows by application in Mission Control
  - action: macos.default
    domain: com.apple.dock
    key: expose-group-by-app
    kind: bool
    value: "false"

  # Don't show Dashboard as a Space
  - action: macos.default
    domain: com.apple.dock
    key: dashboard-in-overlay
    kind: bool
    value: "false"

  # Don't automatically rearrange Spaces based on most recent use
  - action: macos.default
    domain: com.apple.dock
    key: mru-spaces
    kind: bool
    value: "false"

  # Remove the auto-hiding Dock delay
  - action: macos.default
    domain: com.apple.dock
    key: autohide-delay
    kind: float
    value: "0"

  # Remove the animation when hiding/showing the Dock
  - action: macos.default
    domain: com.apple.dock
    key: autohide-time-modifier
    kind: float
    value: "0"

  # Automatically hide and show the Dock
  - action: macos.default
    domain: com.apple.dock
    key: autohide
    kind: bool
    value: "true"

  # Make Dock icons of hidden applications translucent
  - action: macos.default
    domain: com.apple.dock
    key: showhidden
    kind: bool
    value: "true"

  # Don't show recent applications in Dock
  - action: macos.default
    domain: com.apple.dock
    key: show-recents
    kind: bool
    value: "false"
