depends:
  [
    "./manifests/1-init",
    "./manifests/2-packages",
    "./manifests/3-linuxify",
    "./manifests/4-node",
    "./manifests/4-python",
    "./manifests/4-ruby",
    "./manifests/5-terminal",
    "./manifests/6-dot-files",
    "./manifests/6-gitconfig",
    "./manifests/6-library",
    "./manifests/6-neovim",
    "./manifests/6-wallpaper",
  ]
actions:
  ###############################################################################
  # Photos                                                                      #
  ###############################################################################
  # Prevent Photos from opening automatically when devices are plugged in
  - action: macos.default
    domain: com.apple.ImageCaptur
    key: disableHotPlug
    kind: bool
    value: "true"
